# Generated by Django 4.1.4 on 2023-01-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
