# Generated by Django 4.1.4 on 2023-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_sharedtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtransaction',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
